export { gameConfig, getOrderedSteps } from "@/config/chapters";
export type { StepWithId } from "@/config/chapters";
export type {
  GameConfig,
  Chapter,
  Step,
  LetterStep,
  EmailStep,
  SmsStep,
  MmsStep,
  WebsiteStep,
  CompanionMessage,
  Trigger,
  AdvanceCondition,
  ComponentName,
  ComponentConfig,
  ComponentConfigMap,
  WayfindingCompassConfig,
  MarkerButtonConfig,
  MultipleChoiceConfig,
  NarrativeMomentConfig,
  CompassPuzzleConfig,
  PuzzleSolveConfig,
  RewardRevealConfig,
  WaitingStateConfig,
  PassphrasePuzzleConfig,
  HintItem,
  QuestionItem,
  Contact,
  OrderContact,
  CompanionSlot,
  Recipient,
  AdHocRecipient,
  SideEffect,
  Track,
} from "@/config/types";
