-- ─── Admin Auth User ───────────────────────────────────────────────────────────
-- Seed a Supabase Auth user for admin login (local dev only)
-- Password: "Password123!" — local dev only, never use in production
-- Note: The bcrypt hash below was generated by GoTrue's Admin API. Do NOT use
-- pgcrypto's crypt() — it produces hashes that GoTrue cannot verify.
INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  confirmation_token, recovery_token,
  email_change, email_change_token_new, email_change_token_current,
  phone, phone_change, phone_change_token,
  reauthentication_token,
  raw_app_meta_data, raw_user_meta_data, is_super_admin, is_sso_user, is_anonymous
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'authenticated',
  'authenticated',
  'bpaksi@gmail.com',
  '$2a$10$9PNDaDIon580DL0FK0Pf6uabaPvxuIvQCoLSMp4YJmJjN/XMP/SCK',
  now(), now(), now(),
  '', '',
  '', '', '',
  '', '', '',
  '',
  '{"provider":"email","providers":["email"]}',
  '{"email_verified":true}',
  false, false, false
);

INSERT INTO auth.identities (
  id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
) VALUES (
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'bpaksi@gmail.com',
  '{"sub":"a1b2c3d4-e5f6-7890-abcd-ef1234567890","email":"bpaksi@gmail.com","email_verified":false,"phone_verified":false}',
  'email', now(), now(), now()
);
