-- ─── Admin Auth User ───────────────────────────────────────────────────────────
-- Seed a Supabase Auth user for admin login (matches ADMIN_EMAIL in .env.local)
-- Password: "Password123!" — local dev only, never use in production
-- Note: The bcrypt hash below was generated by GoTrue's Admin API. Do NOT use
-- pgcrypto's crypt() — it produces hashes that GoTrue cannot verify.
INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  confirmation_token, recovery_token,
  email_change, email_change_token_new, email_change_token_current,
  phone, phone_change, phone_change_token,
  reauthentication_token,
  raw_app_meta_data, raw_user_meta_data, is_super_admin, is_sso_user, is_anonymous
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'authenticated',
  'authenticated',
  'bpaksi@gmail.com',
  '$2a$10$9PNDaDIon580DL0FK0Pf6uabaPvxuIvQCoLSMp4YJmJjN/XMP/SCK',
  now(), now(), now(),
  '', '',
  '', '', '',
  '', '', '',
  '',
  '{"provider":"email","providers":["email"]}',
  '{"email_verified":true}',
  false, false, false
);

INSERT INTO auth.identities (
  id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
) VALUES (
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'bpaksi@gmail.com',
  '{"sub":"a1b2c3d4-e5f6-7890-abcd-ef1234567890","email":"bpaksi@gmail.com","email_verified":false,"phone_verified":false}',
  'email', now(), now(), now()
);

-- Sample lore entries (always-unlocked Scrolls of Knowledge)
INSERT INTO lore_entries (title, content, unlock_chapter_id, "order") VALUES
  ('The Founding of the Order',
   'Long before the great museums rose from marble and ambition, a secret fellowship gathered in candlelit chambers. They called themselves the Order of the Gilt Frame, sworn to preserve beauty that the careless world would forget. Their first act was to commission a frame of impossible craftsmanship — gold leaf over ancient oak, carved with symbols only the worthy could read.',
   NULL, 1),
  ('The Language of Markers',
   'The Order communicates through Markers — symbols placed in the world for those with eyes to see. Each Marker contains an hourglass formed by two crossing curves, representing the passage of time and the persistence of art. When you find a Marker, you have found a threshold. What lies beyond is yours to discover.',
   NULL, 2),
  ('The Sparrow''s Role',
   'In the Order''s hierarchy, the Sparrow is the seeker — the one who moves between worlds, carrying fragments of truth from one trial to the next. The Sparrow is not chosen by blood or rank, but by the quality of their seeing. To be named Sparrow is to be entrusted with the Order''s most sacred task: to prove that beauty endures.',
   NULL, 3),
  ('The Compass and Its Secrets',
   'The compass is the Order''s oldest instrument. Not merely a tool for navigation, it is a cipher. Every bearing the Order assigns points toward the next revelation. The needle does not merely find north — it finds meaning. Those who follow the compass with patience will discover that every direction was chosen with purpose.',
   'ch1', 4);
