export { gameConfig, getOrderedSteps } from "./config";
export type { StepWithId } from "./config";
export { COMPONENT_ADVANCE } from "./types";
export type {
  Contact,
  CompanionSlot,
  Recipient,
  AdHocRecipient,
  Track,
  GameConfig,
  Chapter,
  Step,
  LetterStep,
  LetterStepConfig,
  EmailStep,
  EmailStepConfig,
  SmsStep,
  SmsStepConfig,
  WebsiteStep,
  CompanionMessage,
  Trigger,
  AdvanceCondition,
  ComponentName,
  ComponentConfig,
  ComponentConfigMap,
  WayfindingCompassConfig,
  MarkerButtonConfig,
  MultipleChoiceConfig,
  CompassPuzzleConfig,
  RewardRevealConfig,
  PassphrasePuzzleConfig,
  HintItem,
  QuestionItem,
} from "./types";
